service: karma-monitor

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Resource: "*"
      Action:
        - ses:SendEmail

functions:
  check:
    handler: handler.run
    events:
      - schedule: rate(5 minutes)