service: karma-monitor

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: prod
  timeout: 3 # Reddit APIs can take a long time to respond
  iamRoleStatements:
    - Effect: Allow
      Resource: "*"
      Action:
        - ses:SendEmail

package:
  individually: true

functions:
  check:
    handler: handler.run
    events:
      - schedule: rate(10 minutes)
    reservedConcurrency: 1

resources:
  Resources:
    MemoryUsedMetricFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: "/aws/lambda/${self:service}-${self:provider.stage}-check"
        FilterPattern: '[report_prefix="REPORT", ..., max_memory_used_prefix="Used:", max_memory_used,max_memory_used_unit="MB"]'
        MetricTransformations:
        - MetricValue: "$max_memory_used"
          MetricNamespace: Lambda
          MetricName: Memory

custom:
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-prune-plugin
  - serverless-plugin-optimize
